HNL/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from blog import urls as blog_urls
from users import urls as user_urls
from classroom import urls as classroom_urls
from chatroom import urls as chatroom_urls

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include(blog_urls)),

    path('users/', include(user_urls)),

    path('classroom/', include(classroom_urls)),

    path('chatroom/', include(chatroom_urls)),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from users.views import *


urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('register/', register, name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify-user/<uidb64>/<token>/', VerificationView.as_view(), name='verification-view'),

    path('complete/profile/<int:pk>/', complete_user_registration, name='complete-user'),
    path('hashTag/', hash_tags, name='hashTag'),
    path('get_field_namings/', get_registration_field_namings, name='fieldNamings'),
    path('stringMatcher/', string_matcher, name='stringMatcher'),
    path('profile/<int:user_pk>/', user_profile_view, name='userProfile'),
    path('profile_data/', get_user_profile_data, name='profile_data'),
    path('auto-complete/', get_names, name='auto-complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator
from django.db.models import Q
from bulk_update_or_create import BulkUpdateOrCreateQuerySet
from classroom.models import *


class Image(models.Model):
    image = models.ImageField(blank=False, null=True,
                              default='default.png', upload_to='teacher_profile_images')

    def __repr__(self):
        return f"{self.image}"

    def __str__(self):
        return f"Path on localhost : {self.image.url}"


class HashTag(models.Model):

    hashTag = models.CharField(max_length=55)
    objects = BulkUpdateOrCreateQuerySet.as_manager()

    def __repr__(self):
        return f"{self.hashTag}"

    def __str__(self):
        return self.hashTag


class Title(models.Model):
    title = models.CharField(max_length=55)

    def __repr__(self):
        return f"{self.title}"

    def __str__(self):
        return self.title


class UserStatus(models.Model):
    userStatus = models.CharField(max_length=55, choices=(
        ('student', 'student'),
        ('teacher', 'teacher')
    ))

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __repr__(self):
        return f"{self.userStatus}"


class Platform(models.Model):
    platform_choices = (
        ('', ''),
        ('Google Meet', 'Google Meet'),
        ('Microsoft Teams', 'Microsoft Teams'),
        ('Zoom', 'Zoom'),
        ('Facebook Messenger', 'Facebook Messenger'),
        ('Other', 'Other')
    )
    platform = models.CharField(blank=False, null=False, max_length=55, choices=platform_choices)

    def __repr__(self):
        return f"{self.platform}"

    def __str__(self):
        return self.platform


class BasicAbstractProfile(models.Model):
    description = models.TextField(blank=False, null=True, max_length=6000)
    hashTag = models.ManyToManyField(HashTag)
    image = models.OneToOneField(Image, on_delete=models.SET_NULL, null=True)
    timeGraph = models.OneToOneField(TimeGraph, on_delete=models.SET_NULL, null=True)
    is_verified_by_email = models.BooleanField(default=False)
    friends = models.ManyToManyField(User, related_name='friends', blank=True)
    record_creation_datetime = models.DateTimeField(editable=True, auto_now=True)

    user_status = models.ForeignKey(UserStatus, editable=False, on_delete=models.CASCADE)
    user = models.OneToOneField(User, null=False, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        self.user_status = self.user.userstatus
        super().save(*args, **kwargs)

    def get_description(self):
        return self.description[:300]

    def __repr__(self):
        return f"{self.user.username}"


class StudentProfile(BasicAbstractProfile):
    def __repr__(self):
        return f"{self.user.username}"


class TeacherProfile(BasicAbstractProfile):
    birth_date = models.DateField(blank=False, null=False)
    full_name = models.CharField(blank=False, null=False, max_length=55)
    lecture_price = models.FloatField(
        blank=False, null=False, validators=[MaxValueValidator(10000)]
    )

    title = models.ForeignKey(Title, on_delete=models.SET_NULL,
                              blank=False, null=True, max_length=55, default='')

    platform = models.ForeignKey(Platform, on_delete=models.SET_NULL,
                                 blank=False, null=True, max_length=55)

    def __str__(self):
        return f"{self.full_name}'s Profile."

    #
    def get_relationship_counts(self):
        return Relationship.objects.filter(
            Q(sender=self.user) | Q(receiver=self.user),
            is_confirmed=True
        ).count()

    def get_feedbacks_count(self):
        return Feedback.objects.filter(
            receiver=self.user
        ).count()

    def get_rating(self):

        if self.get_feedbacks_count() == 0:
            return 0

        all_feedbacks = set(
            Feedback.objects.filter(
                receiver=self.user
            ).values_list("rating", flat=True)
        )

        return sum(all_feedbacks) / len(all_feedbacks)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.db import models
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from users.models import UserProfile, Platform


class UserRegisterForm(UserCreationForm):
    email = models.EmailField(unique=True, null=False, blank=False)

    class Meta:
        model = User
        fields = ['email', 'username', 'password1', 'password2']
        widgets = {
            'email': forms.EmailInput(attrs={'required': 'required'})
        }

    def clean(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("Email exists")


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ['birth_date', 'full_name', 'lecture_price',
                  'description', 'platform', 'title']
        widgets = {
            'birth_date': forms.DateInput(attrs={'required': 'required', 'type': 'date'}),
            'description': forms.Textarea(attrs={"style": "resize: none"})
        }

    def __init__(self, *args, **kwargs):
        # user = kwargs.pop('user', '')
        super(UserProfileForm, self).__init__(*args, **kwargs)

        self.fields['platform'] = forms.ModelChoiceField(
            queryset=Platform.objects.all().values_list('platform', flat=True)
        )

users/views.py
import json

from django.views.generic import View
from django.shortcuts import render, redirect, HttpResponse, Http404
from django.urls import reverse
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.utils.http import urlsafe_base64_decode
from django.http import JsonResponse
from django.utils.encoding import force_str
from django.db.models import Q

from .forms import TeacherRegisterForm, TeacherProfileForm, StudentProfileForm

from .namings import STUDENT_PROFILE_FIELD_IDS_IN_FRONT,\
    TEACHER_FIELD_IDS_IN_FRONT, M2M_FIELDS, FOREIGN_KEY_FIELDS

from .services import get_user_profile_from_cache
from .memcache_helpers import set_key

from users.models import UserStatus, TeacherProfile, Image, StudentProfile, HashTag

from .helpers import parse_values_from_lists_when_ajax_resp,\
    validate_image, create_foreign_keys_where_necessary,\
    get_request_user_profile_model_and_fields,\
    get_user_profile_data,\
    email_verification

from classroom.services import get_booking_requests
from classroom.models import *


class VerificationView(View):
    def get(self, request, uidb64, token):

        user_id = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=user_id)

        user_profile_obj = get_request_user_profile_model_and_fields(user)['profile_obj']

        user_profile_obj.is_verified_by_email = True
        user_profile_obj.save()

        return redirect('userProfile', user.pk)


@login_required
def get_names(request):
    field = request.GET.get('field').split("-")[0]
    search = request.GET.get('search')

    field_class = FOREIGN_KEY_FIELDS[field]
    query_str = f"{field}__startswith"

    payload = []

    if search:
        objs = field_class.objects.filter(
            **{query_str: search}
        )
        for obj in objs:
            payload.append(
                {'name': obj.platform}
            )
    print(payload)
    return HttpResponse(
        json.dumps({
            'status': True,
            'payload': payload,
        })
    )


@login_required
def user_profile_view(request, user_pk=None):

    context = {

    }

    requested_user = User.objects.get(pk=user_pk)  # User who's profile is requested to see
    request_user = request.user  # Just request user.

    if request.method == "GET":

        context = get_user_profile_from_cache(requested_user.username) or {}

        if not context:

            context['fields_data'] = get_user_profile_data(requested_user)
            context['requested_user'] = requested_user

            context['bookingRequests'] = get_booking_requests(
                **{"receiver_id": requested_user.id, "is_confirmed": False}
            )

            context["feedbacks"] = Feedback.objects.filter(
                receiver=request.user
            )

            # Check if users already have a relationship
            context['related'] = Relationship.objects.filter(
                Q(sender=request_user, receiver=requested_user) |
                Q(sender=requested_user, receiver=request_user)
            ).exists()

            # set_key(requested_user.username, context)

        return render(request, "users/profile.html", context=context)

    if request.method == "POST":
        try:

            if request_user == requested_user:
                data = parse_values_from_lists_when_ajax_resp(dict(request.POST))
                profile_model = get_request_user_profile_model_and_fields(requested_user)['model_class']
                data = create_foreign_keys_where_necessary(profile_model, data)

                profile_model.objects.filter(user=requested_user).update(
                    **data
                )

                return HttpResponse(
                    json.dumps({
                        "status": 200,
                        "message": "Successfully updated"
                    })
                )

            return HttpResponse(
                json.dumps({
                    "status": 404,
                    "message": "Invalid Request"
                })
            )

        except Exception as e:
            print(e)
            return HttpResponse(
                json.dumps({
                    "status": 204,
                    "message": "Please, fill in correct data"
                })
            )


class Login(LoginView):
    template_name = 'users/login.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("main-view")
        return super().get(request)


def register(request):
    if request.user.is_authenticated:
        return redirect("main-view")

    form = TeacherRegisterForm
    if request.method == 'POST':
        form = TeacherRegisterForm(request.POST)
        if form.is_valid():
            form.save()

            user_data = form.cleaned_data

            registered_user = User.objects.get(username=user_data['username'])

            UserStatus.objects.create(user=registered_user, userStatus=request.POST['userStatus'])

            new_user = authenticate(username=user_data['username'],
                                    password=user_data['password1'],
                                    )

            login(request, new_user)
            return redirect('complete-user', registered_user.pk)

    return render(request, 'users/register.html', {'form': form})


def get_registration_field_namings(request):
    if request.user.userstatus.userStatus == 'student':
        helpers = STUDENT_PROFILE_FIELD_IDS_IN_FRONT
    else:
        helpers = TEACHER_FIELD_IDS_IN_FRONT

    return HttpResponse(json.dumps(helpers))


@login_required
def hash_tags(request):

    if request.method == "POST":

        key = "hashTag"
        request_data = request.POST
        data = request_data.getlist(key + "[]")
        items = [HashTag(hashTag=hash_tag) for hash_tag in data]

        try:

            HashTag.objects.bulk_update_or_create(
                items, [key], match_field="hashTag"
            )

            committed_and_saved_data = list(
                HashTag.objects.filter(hashTag__in=data)
            )

            request.user.basicabstractprofile.hashTag.add(
                *committed_and_saved_data
            )

            url = reverse("main-view")
            return JsonResponse(status=200, data={'success': url})

        except Exception as e:
            print(e)

    return render(request, 'users/hashTags.html')


# @csrf_exempt
@login_required
def complete_user_registration(request, pk):  # User's Primary key

    if request.user.pk != pk:
        return redirect('main-view')

    user_status = UserStatus.objects.get(user=request.user).userStatus

    if user_status == 'student':
        form = StudentProfileForm

    else:
        form = TeacherProfileForm

    if request.method == 'POST':

        data = parse_values_from_lists_when_ajax_resp(dict(request.POST))
        data['user'] = request.user

        if validate_image(request.FILES['file1']):
            image_obj = Image.objects.create(image=request.FILES['file1'])
            data['image'] = image_obj

        data = create_foreign_keys_where_necessary(form.Meta.model, data)

        form.Meta.model.objects.create(**data)
        email_verification(request, pk)
        url = reverse('hashTag')

        return JsonResponse(status=302, data={'success': url})

    user_full_name = request.user.first_name + ' ' + request.user.last_name
    # return redirect("register")
    return render(request, 'users/complete_user.html',
                  {'form': form, 'full_name': user_full_name})


@login_required
def string_matcher(request):

    user_input = request.GET['inputData']
    suggestions = list(
        HashTag.objects.filter(
            hashTag__icontains=user_input).values_list("hashTag", flat=True)
    )

    return HttpResponse(
        json.dumps(
            {
                "suggestions": suggestions
            }
        )
    )

users/templates/users/complete_user.html
{% extends 'blog/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block link %}
    <link rel="stylesheet" href="{% static 'users/css/register.css' %}">
    <link href="http://netdna.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'users/css/complete_user.css' %}">
{% endblock link %}

{% block content %}
      {% csrf_token %}
      {{ request.user.id|json_script:"user_id" }}
      <div id="login-box">
      {% block hashTag %} {% endblock hashTag %}
      <form enctype="multipart/form-data" onsubmit="onFormSubmit(event)">
         <div class="left">

             <div class="container">
                 <div class="row form-group">
                     <img src="{% static 'users/images/default.jpg' %}" alt="avatar" id="avatar-img">
                    <div class="col-lg-12">
                        <label>Select Profile Picture: </label>
                        <input type="file" name="file1" id="file1">
                    </div>

                 </div>

            <label for="id_description">About you: (3000 words)</label>
            {% render_field form.description class="about-me" style=" width: 450px; height: 125px; background: rgba(0, 0, 0, 0.5); opacity: 50%" %}
             </div>
            </div>
         <div class="right">
                <label for="id_birth_date">Birth date:</label>
                {{ form.birth_date }}
                <label for="id_full_name">Full name:</label>
                {% render_field form.full_name value=full_name %}
                <label for="id_title">Title:</label>
                <input type="text" name="title" required="" id="id_title">
                <label for="id_lecture_price">Monthly fee:</label>
                {{ form.lecture_price }}
                <label for="id_platform">Platform: (Primary)</label>
                {{ form.platform }}

            <button type="submit" class="btn btn-success">Next ></button>
         </div>
        </form>
       </div>

    <script src="{% static 'users/js/complete-user.js' %}"></script>

{% endblock content %}

users/templates/users/hashTags.html
{% extends 'blog/base.html' %}
{% load static %}
{% block link %}
{#    <link rel="stylesheet" href="{% static 'users/register.css' %}">#}
    <link rel="stylesheet" href="{% static 'users/css/hashTags.css' %}">
{#    <link rel="stylesheet" href="https://unicons.ico/nscout.com/release/v4.0.0/css/thinline.css">#}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

{% endblock link %}

{% block content %}
<div id="login-box">
    {% csrf_token %}
    <div class="wrapper" id="hashTag-div">
      <div class="title">
        <img src="{% static 'users/images/tag.png' %}" alt="icon" style="width: 30px; height: 30px">
        <h2>Tags</h2>
      </div>
      <div class="content">
        <p>Press enter or add a comma after each tag</p>
        <ul id="hashTags"><input type="text" spellcheck="false" id="userInputTags"></ul>
        <ul id="suggestions"></ul>
      </div>
      <div class="details">
        <p><span>10</span> tags are remaining</p>
        <button>Remove All</button>
      </div>
    </div>
    <button type="submit" id="register" class="btn btn-success" style="margin: 30px 0 0 420px; font-size: 20px">REGISTER</button>
</div>
<script src={% static 'users/js/hashTags.js' %}></script>
{% endblock content %}

users/templates/users/login.html
{% extends 'blog/base.html' %}
{% load static %}
{% block link %}
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'users/css/register.css' %}">
{% endblock link %}
{% block content %}
          <div id="login-box" style="width: 700px; height: 500px;">
         <div class="left">
             <form method="post">
                 {% csrf_token %}
           <h1 style="margin-top: 20px">Sign In</h1>
           {{ form }}

             <button type="submit" name="signup_submit" value="Sign me up" class="btn btn-success">Submit</button>
                 <p style="font-size: 12px">Have not account yet? <a href="{% url "register" %}" style="text-decoration: none">Sign Up</a></p>
             </form>
         </div>

         <div class="right">
           <span class="loginwith">Sign in with<br />social network</span>
{#            {% include "socialaccount/snippets/provider_list.html" with process="login" %}#}
           <button class="social-signin facebook">Log in with facebook</button>
           <button class="social-signin twitter">Log in with Twitter</button>
           <button class="social-signin google">
               <a style="color: white" href="/accounts/google/login/?process=login">Log in with Google</a></button>
         </div>
         <div class="or">OR</div>
       </div>
{% endblock content %}

users/templates/users/profile.html
{% extends 'blog/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block link %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="http://netdna.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <script src="https://unpkg.com/@trevoreyre/autocomplete-js"></script>
{#    <link#}
{#      rel="stylesheet"#}
{#      href="https://unpkg.com/@trevoreyre/autocomplete-js/dist/style.css"#}
{#    />#}
    <link rel="stylesheet" href="{% static 'users/css/profile.css' %}">
{% endblock link %}

{% block content %}


{% if request.user == requested_user %}

    {% for booking in bookingRequests %}
{#        json.{{ foo.sender }}#}
        <div class="alert alert-success" role="alert">
            You've new request from <a href="{% url 'userProfile' booking.sender.id  %}">
            {{ booking.sender.username }}</a> - see offered times <a target="_blank"
                href="/classroom/time_table/?booking_pk={{ booking.pk }}">Here</a>
            <button type="button" class="btn btn-success"
                    value="true" data-sender_id={{ booking.sender.id }}
                    onclick="func(this)">Approve</button>
            <button type="button" class="btn btn-danger"
                    value="false" data-sender_id={{ booking.sender.id }}
                    onclick="func(this)">Decline</button>
        </div>
    {% endfor %}


{% endif %}

<div class="container" style="margin-top: 10px">
    {{ request.user.id|json_script:"request_user_id" }}
    {{ requested_user.id|json_script:"requested_user_id" }}
    {{ fields_data|json_script:"fields_data" }}
    <form method="post">
    {% csrf_token %}
    <div class="main-body">
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center" id="profile_img">
                    <div class="mt-3">
                    </div>
                  </div>
                </div>
              </div>
              <div class="card mt-3">
                <ul class="list-group list-group-flush" id="feedbacks_ul">
                </ul>
              </div>
                <div class="card mt-3">
                    {% if requested_user == request.user %}
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                        <h6><a style="text-decoration: none; margin-left: 100px;" target="_blank" href="{% url 'time_table' request.user.pk%}">
                            See time table</a></h6>
                        <span class="text-secondary"></span>
                      </li>

                      <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap" style="display:block; margin: 0 auto;">
                            <button id="save-btn" type="button" onclick="save_changes()" class="btn btn-success" style="position: center">Save for any changes
                            </button>
                      </li>
                    {% else %}
                        {% if related %}
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <button id="feedback-btn" type="button" class="btn btn-info" style="margin-left: 5px; width: 350px" onclick="redirecter(this.id)">LEAVE FEEDBACK</button>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <button id="dm-btn" type="button" class="btn btn-warning" style="margin-left: 5px; width: 350px" onclick="redirecter(this.id)">✉️</button>
                            </li>
                        {% else %}
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <button id="book-btn" type="button" class="btn btn-danger" style="margin-left: 5px; width: 350px" onclick="redirecter(this.id)">BOOK</button>
                            </li>
                        {% endif %}
                    {% endif %}
                    </ul>
                </div>

            </div>
            <div class="col-md-8">
              <div class="card mb-3" style="width: 715px">
                <div class="card-body" id="user-fields">
                </div>
              </div>
              <div class="row gutters-sm">
                <div class="col-sm-6 mb-3">
                  <div class="card h-100" style="width: max-content; height: 315px;">
                    <div class="card-body" style="width: 715px" id="textarea-description">
                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">assignment</i>About Me</h6>
                    </div>
                  </div>
                </div>
              </div>
            <div>
            </div>
            </div>
          </div>


        <p style="margin-left: 400px; margin-top: 50px; font-size: 50px">Last Feedbacks</p>
        {% for feedback in feedbacks %}
            <div class="feedback" style="display: inline-block; width: 100%; text-align: center;
             border: 1px solid; border-radius: 5px; padding: 10px; margin: 30px 50px 0 30px">
                <div style="margin-right: auto; margin-bottom: 5px; border-bottom: 1px solid yellow;">
                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle"
                    style="width: 30px; height: 30px; display: inline-block; margin-left: auto;">
                    <p style="display: inline-block; font-size: small;">{{ feedback.sender }} | {{ feedback.date }}</p>
                </div>
                <p>{{ feedback.textFeedback }}</p>
                <div class="stars">
                    {% for i in "x"|rjust:feedback.rating %}
                        <label for="star-1" class="star-1 fas fa-star" style="font-size: 17px; color: yellow"></label>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}



        </div>
    </form>

</div>

<script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<script type="text/javascript"></script>
<script src="{% static 'users/js/profile.js' %}"></script>




<script>

function redirecter(arg) {
    if (arg.includes("book")) {
        location.href = "{% url "time_table" requested_user.id %}"
    }
    else if (arg.includes("feedback")) {
        location.href = "{% url "classroom" %}"
    }
    else if (arg.includes("dm")) {
        location.href = "{% url "chat_room" %}"
    }
}

function func(arg){
    parentDiv = arg.parentNode
    parentDiv.remove()

      $.ajax(
            {
            url: "{% url "response_booking" %}",
            type: 'POST',
            data: {
                is_confirmed: arg.value,
                sender_id: arg.getAttribute("data-sender_id"),
                receiver_id: request_user_id,
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            },
            success: function (response){
                console.log(response);
        }
      });

    }
</script>


{% endblock content %}


users/templates/users/register.html
{% extends 'blog/base.html' %}
{% load static %}
{% block link %}
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'users/css/register.css' %}">
{% endblock link %}

{% block content %}
          <div id="login-box" style="width: 700px; height: 500px;">
         <div class="left">
             <form method="post">
                 {% csrf_token %}
                 <h1>Sign up</h1>
                 {{ form }}

                    <button type="submit" name="signup_submit" value="Sign me up" class="btn btn-success">Submit</button>
                    <p style="font-size: 12px">Already have an account? <a href="{% url "login" %}" style="text-decoration: none">Log in</a></p>
             </form>
         </div>

         <div class="right">
           <span class="loginwith">Sign in with<br />social network</span>

           <button class="social-signin facebook">Log in with facebook</button>
           <button class="social-signin twitter">Log in with Twitter</button>
           <button class="social-signin google">
               <a style="color: white" href="/accounts/google/login/?process=login">Log in with Google</a></button>
         </div>
         <div class="or">OR</div>
       </div>
{% endblock content %}